export const initialCustomers = [
  { id: 1, name: 'Анна Коваль', email: 'anna@midas.test', phone: '+380671112233' },
  { id: 2, name: 'Олег Мельник', email: 'oleh@midas.test', phone: '+380502224455' },
  { id: 3, name: 'Марія Шевченко', email: 'maria@midas.test', phone: '+380933336677' },
]

export const initialProducts = [
  {
    id: 11,
    sku: 'PRD-11',
    barcode: '482000110011',
    name: 'Кавомашина Midas Pro',
    type: 'default',
    category: 'Техніка',
    brand: 'Midas',
    unit: 'одиниць',
    warehouse: 'Gorpcore',
    stock: 18,
    cost: 3200,
    price: 4820,
    description: 'Автоматична кавомашина для малого офісу',
  },
  {
    id: 12,
    sku: 'PRD-12',
    barcode: '482000120012',
    name: 'Фільтр для води',
    type: 'default',
    category: 'Витратні матеріали',
    brand: 'AquaLine',
    unit: 'одиниць',
    warehouse: 'Gorpcore',
    stock: 124,
    cost: 410,
    price: 690,
    description: 'Змінний фільтр для кавомашин',
  },
  {
    id: 13,
    sku: 'PRD-13',
    barcode: '482000130013',
    name: 'Набір чашок',
    type: 'set',
    category: 'Аксесуари',
    brand: 'Midas',
    unit: 'комплектів',
    warehouse: 'Gorpcore',
    stock: 41,
    cost: 240,
    price: 420,
    description: 'Набір із чотирьох чашок',
  },
]

export const initialOrders = [
  {
    id: 1,
    code: 'SALE-1007',
    customer: 'Анна Коваль',
    product: 'Кавомашина Midas Pro',
    quantity: 1,
    total: 4820,
    cost: 3200,
    profit: 1620,
    expense: 0,
    status: 'processing',
    operationType: 'sale',
    channel: 'Instagram',
    date: '2026-05-17',
  },
  {
    id: 2,
    code: 'SALE-1008',
    customer: 'Олег Мельник',
    product: 'Фільтр для води',
    quantity: 2,
    total: 1380,
    cost: 820,
    profit: 560,
    expense: 90,
    status: 'draft',
    operationType: 'delivery',
    channel: 'OLX-Наложка',
    date: '2026-05-16',
  },
  {
    id: 3,
    code: 'SALE-1009',
    customer: 'Марія Шевченко',
    product: 'Набір чашок',
    quantity: 4,
    total: 1680,
    cost: 960,
    profit: 720,
    expense: 0,
    status: 'completed',
    operationType: 'sale',
    channel: 'Prom.ua',
    date: '2026-05-10',
  },
]

export const initialChats = [
  {
    id: 1,
    customer: 'Анна Коваль',
    channel: 'Instagram',
    unread: 2,
    lastMessage: 'Чи є в наявності Midas Pro?',
    time: '12:45',
  },
  {
    id: 2,
    customer: 'Олег Мельник',
    channel: 'OLX',
    unread: 0,
    lastMessage: 'Дякую, очікую накладну.',
    time: '11:20',
  },
  {
    id: 3,
    customer: 'Марія Шевченко',
    channel: 'Instagram',
    unread: 1,
    lastMessage: 'Можна оформити доставку на завтра?',
    time: '09:05',
  },
]

export const initialOperations = [
  {
    id: 1,
    createdAt: '2026-05-17 10:30',
    type: 'Закупівля товару',
    description: 'Додано 18 одиниць товару Кавомашина Midas Pro за собівартістю 3200 грн',
    actor: 'admin@midas.test',
    amount: '57 600 грн',
  },
  {
    id: 2,
    createdAt: '2026-05-16 15:12',
    type: 'Фінансова витрата',
    description: 'Додано витрату на пакування та доставку продажу SALE-1008',
    actor: 'admin@midas.test',
    amount: '90 грн',
  },
]
